### ISSUE TITLE
It's Time

### ISSUE THREAD

**Issue by brady691213** [ernstc/SwitchStartupProject2022#3]
I think you should archive this repo. VS now has equivalent, better functionality, and you are not active on the project.

**Comment by ernstc** [comment]
Hi, this repo is a fork of the original one. The fork was needed for supporting also VS on ARM and doing some fixes to the original extension. At the moment there is no plan to evolve it with new features. But, whoever want to add something, is welcome. Who want to use it as it is, is welcome. I contribute on it on my spare time. Anyway, I will leave it open for security fixes.
